name: update-forks 

on:
  repository_dispatch:
    types: [org-workflow-bot]  
   
jobs:
  update-forks:
    runs-on: ubuntu-latest
    name: register the workflow
    steps:
    - uses: SvanBoxel/organization-workflow@main
      with:
        id: ${{ github.event.client_payload.id }}
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        run_id: ${{ github.run_id }}
        name: ${{ github.workflow }} # Default: name of workflow. This name is shown with the check, but can be changed.
        
    - echo "Hello World"
