name: update-forks 

on:
  repository_dispatch:
    types: [org-workflow-bot]  
   
jobs:
  register:
    runs-on: ubuntu-latest
    name: register the workflow
    steps:
    - uses: SvanBoxel/organization-workflow@main
      with:
        id: ${{ github.event.client_payload.id }}
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        run_id: ${{ github.run_id }}
        name: ${{ github.workflow }} # Default: name of workflow. This name is shown with the check, but can be changed.
    
  main:
    needs: [register]
    runs-on: ubuntu-latest
    steps:
    # checkout the repo that triggered this workflow, through the app
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        repository: ${{ github.event.client_payload.repository.full_name }}
        ref: ${{ github.event.client_payload.sha }}
        token: ${{ github.event.client_payload.token }}
    - echo "Hello World"
